baseURL = "https://rc-web-crawler.github.io/"
languageCode = 'en-us'
title = 'Web Crawler'
theme="hugo-theme-learn"
relativeurls = true

[params]
  themeVariant = "green"
  titleSeparator = ":"
  showVisitedLinks = false

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[Languages]
[[Languages.en.menu.shortcuts]]
  name = "<i class='fab fa-fw fa-github'></i> GitHub"
  identifier = "ds"
  url = "https://github.com/RC-Web-crawler/Hugo-site"
  weight = 10

[[Languages.en.menu.shortcuts]]
  name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
  url = "/credits"
  weight = 20